if (!this.sh_languages) {
    this.sh_languages = {};
}
sh_languages['alg'] = [
    [
        [
            /(^|\s)(?:this|Ввести|Вывести|Делать|пока|Если|конец|закончить|программу|иначе|делится|на|то|разделить)(?=\s|$)/gi,
            'sh_keyword',
            -1
        ],
        [
            /\(\*/g,
            'sh_comment',
            1
        ],
        [
            /\{/g,
            'sh_comment',
            2
        ],
        [
            /\b[+-]?(?:(?:0x[A-Fa-f0-9]+)|(?:(?:[\d]*\.)?[\d]+(?:[eE][+-]?[\d]+)?))u?(?:(?:int(?:8|16|32|64))|L)?\b/g,
            'sh_number',
            -1
        ],
        [
            /"/g,
            'sh_string',
            3
        ],
        [
            /'/g,
            'sh_string',
            4
        ],
        [
            /(^|\s)(?:boolean|вывод|byte|char|integer|maxint|real)(?=\s|$)/gi,
            'sh_type',
            -1
        ],
        [
            /~|!|%|\^|\*|\(|\)|-|\+|=|\[|\]|\\|:|;|,|\.|\/|\?|&|<|>|\|/g,
            'sh_symbol',
            -1
        ],
        [
            /(?:[A-Za-z]|_)[A-Za-z0-9_]*(?=[ \t]*\()/g,
            'sh_function',
            -1
        ]
    ],
    [
        [
            /\*\)/g,
            'sh_comment',
            -2
        ],
        [
            /\(\*/g,
            'sh_comment',
            1
        ]
    ],
    [
        [
            /\}/g,
            'sh_comment',
            -2
        ],
        [
            /\{/g,
            'sh_comment',
            2
        ]
    ],
    [
        [
            /$/g,
            null,
            -2
        ],
        [
            /\\(?:\\|")/g,
            null,
            -1
        ],
        [
            /"/g,
            'sh_string',
            -2
        ]
    ],
    [
        /*    [
         /$/g,
         null,
         -2
         ], */
        [
            /\\(?:\\|')/g,
            null,
            -1
        ],
        [
            /'/g,
            'sh_string',
            -2
        ]
    ]
];
